=== liweisnake/storefront/hpsdf-ngp-application-rpm/src/main/software/jboss/server/all/deploy/jboss-portal.sar/dtd/profile-config_2_6.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~ JBoss, a division of Red Hat                                              ~
  ~ Copyright 2006, Red Hat Middleware, LLC, and individual                   ~
  ~ contributors as indicated by the @authors tag. See the                    ~
  ~ copyright.txt in the distribution for a full listing of                   ~
  ~ individual contributors.                                                  ~
  ~                                                                           ~
  ~ This is free software; you can redistribute it and/or modify it           ~
  ~ under the terms of the GNU Lesser General Public License as               ~
  ~ published by the Free Software Foundation; either version 2.1 of          ~
  ~ the License, or (at your option) any later version.                       ~
  ~                                                                           ~
  ~ This software is distributed in the hope that it will be useful,          ~
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of            ~
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU          ~
  ~ Lesser General Public License for more details.                           ~
  ~                                                                           ~
  ~ You should have received a copy of the GNU Lesser General Public          ~
  ~ License along with this software; if not, write to the Free               ~
  ~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA        ~
  ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.                  ~
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--
<!DOCTYPE profile PUBLIC
   "-//JBoss Portal//DTD JBoss User Profile Configuration 1.0//EN"
   "http://www.jboss.org/portal/dtd/profile-config_2_6.dtd">
-->


<!--<profile>
   --><!--Database mapping - jbp_user table column mapping--><!--
   <property>
      <name>portal.user.name.given</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>mandatory</usage>
      <display-name xml:lang="en">Name</display-name>
      <description xml:lang="en">The user name</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_username</value>
         </database>
      </mapping>
   </property>-->

<!--
.
-->
<!ELEMENT profile (property+) >

<!--
.
-->
<!ELEMENT property (name, type, access-mode, usage, display-name, description, mapping) >

<!--
.
-->
<!ELEMENT name (#PCDATA) >

<!--
.
-->
<!ELEMENT type (#PCDATA)>

<!--
.
-->
<!ELEMENT access-mode (#PCDATA) >

<!--
.
-->
<!ELEMENT usage (#PCDATA) >

<!--
.
-->
<!ELEMENT display-name (#PCDATA) >

<!ATTLIST display-name
          xml:lang CDATA #IMPLIED>

<!--
.
-->
<!ELEMENT description (#PCDATA) >

<!ATTLIST description
          xml:lang CDATA #IMPLIED>
<!--
.
-->
<!ELEMENT mapping (database?, ldap?) >

<!--
.
-->
<!ELEMENT database (type, value) >

<!--
.
-->
<!--<!ELEMENT type (#PCDATA) >-->

<!--
.
-->
<!ELEMENT value (#PCDATA) >

<!--
.
-->
<!ELEMENT ldap (value) >

=== liweisnake/storefront/hpsdf-ngp-application-rpm/src/main/software/jboss/server/production/deploy/jboss-portal-ha.sar/conf/identity/profile-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~ JBoss, a division of Red Hat                                              ~
  ~ Copyright 2006, Red Hat Middleware, LLC, and individual                   ~
  ~ contributors as indicated by the @authors tag. See the                    ~
  ~ copyright.txt in the distribution for a full listing of                   ~
  ~ individual contributors.                                                  ~
  ~                                                                           ~
  ~ This is free software; you can redistribute it and/or modify it           ~
  ~ under the terms of the GNU Lesser General Public License as               ~
  ~ published by the Free Software Foundation; either version 2.1 of          ~
  ~ the License, or (at your option) any later version.                       ~
  ~                                                                           ~
  ~ This software is distributed in the hope that it will be useful,          ~
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of            ~
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU          ~
  ~ Lesser General Public License for more details.                           ~
  ~                                                                           ~
  ~ You should have received a copy of the GNU Lesser General Public          ~
  ~ License along with this software; if not, write to the Free               ~
  ~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA        ~
  ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.                  ~
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!DOCTYPE profile PUBLIC
   "-//JBoss Portal//DTD JBoss User Profile Configuration 1.0//EN"
   "http://www.jboss.org/portal/dtd/profile-config_2_6.dtd">

<profile>
   <!--Database mapping - jbp_user table column mapping-->
   <property>
      <name>user.name.nickName</name>
      <type>java.lang.String</type>
      <access-mode>read-only</access-mode>
      <usage>mandatory</usage>
      <display-name xml:lang="en">Name</display-name>
      <description xml:lang="en">The user's nickname</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_uname</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>user.name.given</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Given Name</display-name>
      <description xml:lang="en">The user's given name</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_givenname</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>user.name.family</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Family name</display-name>
      <description xml:lang="en">The user's family name</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_familyname</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>user.business-info.online.email</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>mandatory</usage>
      <display-name xml:lang="en">Email</display-name>
      <description xml:lang="en">The user's real email</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_realemail</value>
         </database>
         <ldap>
            <value>mail</value>
         </ldap>
      </mapping>
   </property>
   <property>
      <name>portal.user.email.fake</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Fake email</display-name>
      <description xml:lang="en">The user's fake email</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_fakeemail</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.registration-date</name>
      <type>java.util.Date</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Registration date</display-name>
      <description xml:lang="en">The user's registration date</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_regdate</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.email.view-real</name>
      <type>java.lang.Boolean</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">View real email</display-name>
      <description xml:lang="en">Should the user's real email be displayed in public?</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_viewrealemail</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.enabled</name>
      <type>java.lang.Boolean</type>
      <access-mode>read-write</access-mode>
      <usage>mandatory</usage>
      <display-name xml:lang="en">Enabled</display-name>
      <description xml:lang="en">Is user enabled?</description>
      <mapping>
         <database>
            <type>column</type>
            <value>jbp_enabled</value>
         </database>
      </mapping>
   </property>

   <!--Dynamic database store-->
   <property>
      <name>portal.user.location</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Location</display-name>
      <description xml:lang="en">The user's location</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.location</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.occupation</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Occupation</display-name>
      <description xml:lang="en">The user's occupation</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.occupation</value>
         </database>
         <ldap>
            <value>title</value>
         </ldap>
      </mapping>
   </property>
   <property>
      <name>portal.user.extra</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Extra info</display-name>
      <description xml:lang="en">Extra informtion about user</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.extra</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.signature</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Signature</display-name>
      <description xml:lang="en">The user's signature</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.signature</value>
         </database>
         <!--<ldap>
            <value>personalSignature</value>
         </ldap>-->
      </mapping>
   </property>
   <property>
      <name>portal.user.interests</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Interests</display-name>
      <description xml:lang="en">The user's interests</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.interests</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.locale</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">Locale</display-name>
      <description xml:lang="en">The user's locale</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.locale</value>
         </database>
         <!--<ldap>-->
         <!--<value>localityName</value>-->
         <!--</ldap>-->
      </mapping>
   </property>
   <property>
      <name>portal.user.im.icq</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">ICQ</display-name>
      <description xml:lang="en">The user's ICQ id</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.im.icq</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.im.aim</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">AIM</display-name>
      <description xml:lang="en">The user's AIM id</description>
      <mapping>
         <database>
            <type>dynamic</type>
            <value>portal.user.im.aim</value>
         </database>
      </mapping>
   </property>
   <property>
      <name>portal.user.im.msnm</name>
      <type>java.lang.String</type>
      <access-mode>read-write</access-mode>
      <usage>optional</usage>
      <display-name xml:lang="en">MSN</display-name>
      <description xml:lang="en">The user's MSN id</description>
